# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: windows-latest

steps:

- task: UiPathPack@4
  inputs:
    versionType: 'AutoVersion'
    projectJsonPath: '$(Build.SourcesDirectory)'
    outputType: 'Process'
    orchestratorConnection: 'UiPath Orchestrator'
    outputPath: '$(Build.ArtifactStagingDirectory)\Output'
    #runWorkflowAnalysis: true
    traceLevel: 'Verbose'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'DemoRpaChallenge2023CICD'
    publishLocation: 'Container'

#- task: UiPathDeploy@4
#  inputs:
#    orchestratorConnection: 'UiPath Orchestrator'
#    packagesPath: '$(Build.ArtifactStagingDirectory)\Output'
#    folderName: 'Default/Development'
#    traceLevel: 'Verbose'